Installation:
  DBPath: 'where to create db'
  ConfigFile: 'where to save this file'
Communication:
  Interval: 'in seconds'
  Servers:
    - Address: 'address'
      Key: 'c2 password'
    - Address: 'another address'
      Key: 'another c2 key'
Apps:
  Screenshot:
    interval: 300
