installation:
  run_password: 'some password'
  db_path: 'db path'
communication:
  interval: 'in seconds'
  cnc:
    - address: 'address'
      key: 'c2 password'
    - address: 'another address'
      key: 'another c2 key'
persistence: # this won't happen is this round
  enc: 'path to symmetric secret key'
  method: 'provide list of methods and let the user choose, remember to compile only one method'
